### ISSUE TITLE
Instructions on how to run with Grafana Tempo

### ISSUE THREAD

**Issue by bboreham** [weaveworks-experiments/kspan#38]
Filing this issue as a place-holder / reminder for myself.

Grafana Tempo is a trace store that does not index span tags, so the workflow I used with Jaeger doesn't work.
If you send kspan's traces through Grafana Agent its `automatic_logging` feature can spit the trace IDs out, and you can index them using Grafana Loki.

Alternatively it might be better to have kspan log the details for indexing in Loki, because it has more context.

**Comment by bboreham** [comment]
I'm doing ok with this config:
```
    tempo:
        configs:
          - automatic_logging:
                roots: true
                span_attributes: ["namespace", "object"]
```
